findaserver/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponse
from django.shortcuts import render

admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'findaserver.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^robots.txt$', lambda r: HttpResponse(
        "User-agent: *\nDisallow:",
        content_type="text/plain")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls')),
    url(r'^management/', include('management.urls', namespace="management")),
    # url(r'^facebook/', include('django_facebook.urls')),
    url(r'^privacy/$', lambda r: render(r, 'privacy.html')),
    url(r'^', include('servers.urls', namespace='servers')),
]

management/urls.py
from django.conf.urls import include, url
from views import manage_server


urlpatterns = (
    url(r'^server/(?P<server_id>\d+)/$', manage_server, name="server"),
)

servers/urls.py
from django.conf.urls import url, include

from servers import views, server_views, skins, player_views

server_patterns = [
    url(r'^submit/', views.submit_server,
        name="submit"),
    url(r'^(?P<server_id>\d+)/', include([
        url(r'^$', server_views.server_detail,
            name='server_detail'),
        url(
            r'^verify/$', server_views.server_verify, name="server_verify"),
        url(r'^verify/(?P<type>\d)/$',
            server_views.server_verify_check),
        url(r'^players/$',
            views.player_list_with_server),
        url(
            r'^players/(?P<player_uuid>[0-9A-F]{8}'
            '(-[0-9A-F]{4}){3}-[0-9A-F]{12})/$',
            views.player_detail),
    ])),
]

player_patterns = [
    url(r'^$', views.player_list, name="players"),
    url(r'^list/$', player_views.player_list, name="player_list"),
    url(r'^by-username/$', player_views.find_player, name="player_search"),
    url(
        r'^by-username/(?P<username>[0-9A-Za-z_]{0,16})/$',
        player_views.find_player,
        name="find_player"
    ),
    url(r'^name-changes/$', player_views.recent_name_changes),
    url(
        r'^(?P<player_uuid>[0-9A-F]{8}(-[0-9A-F]{4}){3}-[0-9A-F]{12})/',
        include([
            url(r'^$', views.player_detail, name="player_detail"),
            url(r'^verify/$', views.player_verify, name="player_verify"),
            url(r'^verify_token/$', views.player_verify_token),
            url(
                r'^skin/',
                include([
                    url(r'^full.png$', skins.full, name="full_skin"),
                    url(r'^head.png$', skins.head),
                    url(r'^head-(?P<dimension>\d*).png$', skins.head),
                ])
            ),
        ])
    ),

]

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^scripts/ads.js$', views.ad),
    url(r'^servers/', include(server_patterns)),
    url(r'^players/', include(player_patterns)),
    url(r'^stats/$', views.statistics, name="stats"),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout, password_reset, \
    password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib import admin

from users.views import register, self_view, user_detail

admin.autodiscover()

urlpatterns = (
    url(r'^logout/$', logout, name="logout"),
    url(r'^login/$', login, name="login"),
    url(r'^register/$', register, name="register"),
    url(r'^reset/$', password_reset, name="password_reset"),
    url(r'^reset/sent/$', password_reset_done, name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[A-Za-z0-9]*)/(?P<token>.*)/$',
        password_reset_confirm, name="password_reset_confirm"),
    url(r'^reset/complete/$', password_reset_complete,
        name="password_reset_complete"),
    url(r'^me/$', self_view, name='self_view'),
    url(r'^info/(?P<username>[A-Za-z0-9_@+.-]*)/$',
        user_detail, name='user_info'),
)

servers/models.py
from datetime import timedelta

from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings


class Server(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=30)
    port = models.IntegerField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    verification = models.OneToOneField(
        'ServerVerificationKey',
        blank=True,
        null=True,
        related_name="server2"
    )
    score = models.IntegerField(db_index=True, default=0)
    rank = models.IntegerField(db_index=True, blank=True, null=True)
    online_mode = models.NullBooleanField(db_index=True, blank=True, null=True)
    protocol = models.IntegerField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('servers:server_detail', args=[self.pk])


class ServerVerificationKey(models.Model):
    DNS_METHOD = 0
    MOTD_METHOD = 1
    server = models.ForeignKey(Server)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    verification_mode = models.PositiveSmallIntegerField(choices=(
        (DNS_METHOD, 'DNS'), (MOTD_METHOD, 'MOTD'),
    ))
    verification_code = models.CharField(max_length=24)

    class Meta:
        unique_together = (
            ('server', 'user', 'verification_mode'),
            ('server', 'verification_code', ),
        )


class UpTime(models.Model):
    server = models.ForeignKey(Server)
    checkTime = models.DateTimeField(db_index=True)
    status = models.BooleanField(db_index=True)
    playerCount = models.IntegerField()
    delta = models.IntegerField()

    def __unicode__(self):
        return "Uptime of " + self.server.name

    class Meta:
        index_together = (
            ('server', 'status', ),
            ('server', 'checkTime', 'status'),
        )


class UpTimeAggregate(models.Model):
    server = models.ForeignKey(Server)
    checkTime = models.DateTimeField(db_index=True)
    playerCount = models.IntegerField()
    up_time = models.IntegerField()
    total_time = models.IntegerField()

    class Meta:
        unique_together = (('server', 'checkTime', ), )


class QueryError(models.Model):
    server = models.ForeignKey(Server)
    time = models.DateTimeField(db_index=True)
    safe = models.BooleanField(db_index=True)
    description = models.TextField()


class MinecraftAccount(models.Model):
    # Minecraft account UUIDs are stored in 128bits, which needs just less
    # than 39 digits to represent.
    UUID = models.DecimalField(max_digits=39, decimal_places=0, unique=True)
    name = models.CharField(max_length=16, unique=True, blank=True, null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    playson = models.ManyToManyField(Server, through='PlayTime')
    verification_code = models.CharField(max_length=8)

    def __unicode__(self):
        if self.name is not None:
            return self.name
        return "%x" % self.UUID

    def get_absolute_url(self):
        uuid = ('%X' % self.UUID).zfill(32)
        uuid = uuid[:8] + "-" + uuid[8:12] + "-" + uuid[12:16] + "-"
        uuid += uuid[16:20] + "-" + uuid[20:]
        return reverse('servers:player_detail', args=[uuid])


class Names(models.Model):
    minecraft_account = models.ForeignKey(MinecraftAccount)
    name = models.CharField(max_length=16, db_index=True)
    start = models.DateTimeField()
    end = models.DateTimeField(null=True)


class PlayTime(models.Model):
    minecraft_account = models.ForeignKey(MinecraftAccount)
    server = models.ForeignKey(Server)
    end_time = models.DateTimeField(db_index=True)
    duration = models.IntegerField()

    @property
    def start_time(self):
        return self.end_time - timedelta(self.duration)

    def __unicode__(self):
        return unicode(self.minecraft_account) + u" played on " + \
               unicode(self.server) + u" for " + \
               unicode(self.duration) + u" seconds."


class FacebookSync(models.Model):
    playtime = models.OneToOneField(PlayTime)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    fb_id = models.BigIntegerField()


class ExtraServerData(models.Model):
    VOTIFIER = 1
    server = models.ForeignKey(Server)
    type = models.IntegerField(choices=(
        (VOTIFIER, 'Votifier'),
    ), blank=False)
    content = models.TextField()

    class Meta:
        unique_together = (('server', 'type', ), )


class Vote(models.Model):
    minecraft_account = models.ForeignKey(MinecraftAccount, null=True)
    minecraft_name = models.CharField(max_length=16)
    ip = models.GenericIPAddressField(unpack_ipv4=True, db_index=True)
    server = models.ForeignKey(Server)
    time = models.DateTimeField(db_index=True)
    submitted = models.NullBooleanField(db_index=True, null=True, blank=True)

servers/forms.py
import errno
from string import ascii_letters
import socket


from django import forms
from django.forms import ValidationError
from django.utils.safestring import mark_safe

from minecraft.client import fake_client
from servers.models import Server, MinecraftAccount


class SubmitServerForm(forms.Form):
    server_name = forms.CharField(max_length=30)
    address = forms.CharField(max_length=30 + 6)

    def clean_address(self):
        split_addr = self.cleaned_data['address'].split(':')
        if len(split_addr) == 1:
            address = split_addr[0]
            port = 25565
        else:
            address = split_addr[0]
            try:
                port = int(split_addr[1])
            except ValueError:
                raise ValidationError(
                    "The address specified is invalid (':' mis-placed?)")
            if not 0 < port <= 65535:
                raise ValidationError("That port number is invalid.")
        try:
            server = Server.objects.get(address__iexact=address, port=port)
        except Server.DoesNotExist:
            pass
        else:
            raise ValidationError(mark_safe(
                "A server at that address is already tracked <a href=\""
                + server.get_absolute_url()
                + "\">here</a>"
            ))
        test_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        try:
            try:
                test_sock.bind((address, 65535))
            except socket.error as err:
                test_sock.close()
                if err.errno != errno.EADDRNOTAVAIL:
                    raise
            else:
                test_sock.close()
                raise Exception()
        except Exception:
            raise ValidationError("The address provided is invalid.")
        # TODO IPv6
        # TODO Check IPs
        # ip = socket.gethostbyname(address).split(",")
        # servers = Server.objects.filter(ip=ip)
        # if not servers:
        try:
            fake_client.query((address, port), 2)
        except:
            raise ValidationError(
                "Could not query the server specified. "
                "Please check the address"
            )
        else:
            return address, port


class VoteForm(forms.Form):
    account_name = forms.CharField(
        max_length=16)

    def __init__(self, request):
        forms.Form.__init__(self, request.POST if request.POST else None)
        self.mode = False
        if request.user.is_authenticated():
            players = [(p.id, p.name) for p in MinecraftAccount.objects.filter(
                owner=request.user).order_by("name")]
            if players:
                self.fields.update({
                    'account_name': forms.ChoiceField(
                        choices=[
                            ('IMPORT_FROM_OTHER', 'Other (Please Specify)')
                        ] + players
                    ),
                    'other': forms.CharField(
                        max_length=16,
                        required=False
                    ),
                })
                self.mode = True

    def clean_account_name(self):
        if self.mode:
            if self.cleaned_data['account_name'] == "IMPORT_FROM_OTHER":
                try:
                    return self.cleaned_data['other']
                except KeyError:
                    return "IMPORT_FROM_OTHER"
            else:
                self.cleaned_data['account'] = int(
                    self.cleaned_data['account_name'])
                return None
        return self.cleaned_data['account_name']

    def clean_other(self):
        if self.cleaned_data['account_name'] == "IMPORT_FROM_OTHER":
            self.cleaned_data['account_name'] = self.cleaned_data['other']
        return self.cleaned_data['other']


class PlayerVerifyForm(forms.Form):
    token = forms.CharField(max_length=100)


VALID_USERNAME_CHARS = set(ascii_letters) | {'_'}


class PlayerHistoryForm(forms.Form):
    username = forms.CharField(max_length=16)
    add_if_not_exist = forms.CharField(
        initial="",
        widget=forms.widgets.HiddenInput(),
        required=False
    )

    def clean_username(self):
        for char in self.cleaned_data['username']:
            if char not in VALID_USERNAME_CHARS:
                raise ValidationError(
                    "Username has invalid characters. "
                    "Only A-Z 0-9 and _ are allowed."
                )
        return self.cleaned_data['username']

servers/templates/servers/detail.html
{% extends "base.html" %}
{% block title %}{{ server.name }}{% endblock %}
{% block head %}
  <meta property="fb:app_id" content="523587411113451" />
  <meta property="og:type"   content="find-a-server:minecraft_server" />
  {% if canonical %}
  <meta property="og:url"    content="{{ canonical }}" />
  {% else %}
  <meta property="og:url"    content="https://find-a-server.com{{ request.path }}" />
  {% endif %}
  <meta property="og:title"  content="{{ server.name }}" />
  <meta property="og:image"  content="https://find-a-server.com{{ cover_image.0 }}" />
{% endblock head %}
{% block pread %}
<h1 id="server_title" style="background-image: url('{{ cover_image.0 }}'); background-position: {{ cover_image.1 }};"{% if cover_image.2 %} class="alt"{% endif %}>{{ server.name }}
</h1>
<div class="row" style="margin-bottom:10px;">
    <div class="col-sm-6">Address: <kbd>{{ server.address }}{% if server.port != 25565 %}:{{ server.port }}{% endif %}
    </kbd></div>
    <div class="col-sm-3{% if not server.owner %} hidden-xs"><a href="{{ server.get_absolute_url }}verify/">Claim this server</a>{% else %}">Owner: {{ server.owner }} (<a href="{{ server.get_absolute_url }}verify/">Dispute</a>){% endif %}</div>
    <div class="col-sm-3">Up Time: {{ uptime }}</div>
</div>
{% endblock pread %}
{% block body %}
{% load myfilters %}
<div class="row">
    <div class="col-lg-6">
    <div id="player-count-graph"></div>
    </div>
    <div class="col-lg-6">
        <h2>Vote for this Server</h2>
        {% if has_votifier %}
        <p class="bg-success">
            This server has votifier enabled, you may be rewarded in game for your vote.
            {% if votifier_outstanding  %}<br />
            However, there {{ votifier_outstanding|pluralize:"is,are" }} {{ votifier_outstanding }} unsubmitted vote{{ votifier_outstanding|pluralize }}.{% endif %}
        </p>
        {% endif %}
        <p class="bg-info">You have {{ votes_left }} vote{{ votes_left|pluralize}} for this server remaining.</p>
        {% if vote_count < allowed_votes %}
        <form class="form-horizontal vote-form" role="form" method="post" action="{{ server.get_absolute_url }}">
            {% include "form_template.html" with form=vote_form %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-2">
                    <button type="submit" class="btn btn-default">Vote!</button>
                </div>
            </div>
        </form>
        {% else %}
        <p class="bg-warning">
            You have voted over your limit of {{ allowed_votes }} vote{{ allowed_votes|pluralize }} per 24 hours.
            You can next vote in {{ next_expire|timedelta }}.
            {% if user.is_authenticated %}
            {% if not has_ads %}
            You can gain an extra vote by disabling adblock on this website (You will need to refresh the page
            for this to be verified).
            {% endif %}
            {% else %}
            {% if has_ads %}
            You can gain an extra vote by logging in.
            {% else %}
            You can gain extra votes by logging in or by disabling adblock on this website (You will need to refresh
            the page for this to be verified).
            {% endif %}
            {% endif %}
        </p>
        {% endif %}
    </div>
    {% if show_last_playtimes %}
    <div class="col-xs-12">
        <h3>Last 50 Sessions</h3>
    <div id="playtime-graph"></div>
    </div>
    {% endif %}
</div>
<h3>Totals This Week</h3>
<div class="row">
<div class="col-sm-3">Playtime: {% if total_playtime%}{{ total_playtime|timedelta }}{% else %}0 Hours{%endif%}</div>
<div class="col-sm-3">Votes: {{ total_votes }}</div>
<div class="col-sm-3">Players: {{ total_players }}</div>
<div class="col-sm-3">Score: {{ server.score }}</div>
</div>
<div class="col-sm-6 col-lg-3">
    <h2>Top Players this Week</h2>
    {% if top_players %}
    <ul class="list-unstyled player-list">
        {% for player in top_players %}
        <li class="col-xs-12">
            <img src="{{ player.get_absolute_url }}skin/head-64.png" width="64" height="64" alt="Face of {{player}}"/>

            <div>
                <a href="{{ player.get_absolute_url }}">{{ player.name}}</a><br/>{{player.time|timedelta}}
            </div>
        </li>
        {% endfor %}
    </ul>
    <div class="clearfix"></div>
    {% else %}
    <p class="bg-info" style="padding:15px;">
        No players have been tracked on this server, it's possible no one has played here or
        maybe the server doesn't have the advanced query enabled.
    </p>
    {% endif %}
</div>
<div class="col-sm-6 col-lg-3">
    <h2>Top Voters this Week</h2>
    {% if top_voters %}
    <ul class="list-unstyled player-list">
        {% for player in top_voters %}
        <li class="col-xs-12">
            <img src="{{ player.get_absolute_url }}skin/head-64.png" width="64" height="64" alt="Face of {{player}}"/>

            <div>
                <a href="{{ player.get_absolute_url }}">{{ player.name}}</a><br/>{{player.votes}} Votes
            </div>
        </li>
        {% endfor %}
    </ul>
    <div class="clearfix"></div>
    {% else %}
    <p class="bg-info" style="padding:15px;">
        This server has not received any votes. Be the first and your username could be here!
    </p>
    {% endif %}
</div>
<div class="col-sm-6 col-lg-3">
    <h2>Online Now</h2>
    {% if online %}
    <ul class="list-unstyled player-list">
        {% for player in online %}
        <li class="col-xs-12">
            <img src="{{ player.get_absolute_url }}skin/head-64.png" width="64" height="64" alt="Face of {{player}}"/>

            <div>
                <a href="{{ player.get_absolute_url }}">{{ player.name}}</a><br/>
                Playing {% if player.duration%}for {{player.duration|timedelta}}{%else%} just now{%endif %}
            </div>
        </li>
        {% endfor %}
    </ul>
    <div class="clearfix"></div>
    {% else %}
    <p class="bg-info" style="padding:15px;">
        No players have been tracked on this server recently, it's possible no one has played here or
        maybe the server doesn't have the advanced query enabled.
    </p>
    {% endif %}
</div>
{% endblock body %}

servers/templates/servers/index.html
{% extends "base.html" %}
{% block body %}
<h1>Top Servers</h1>
<p>
    These are the servers that Find A Server has ranked highest.
</p><!--
<div class="filters col-md-2">
<h4>Filter</h4>
<p>Use these filters to narrow down your search.</p>
<h5>Current Filters</h5>
<div class="filter-active">
    On-line Mode
</div>
</div> -->
<div class="">
{% if page %}
{% for server in page %}
{% include "servers/snipet.html" %}
{% endfor %}
{% if page.has_other_pages %}
<ul class="pager">
    {% if page.has_previous %}
    <li><a href="{% url 'servers:index' %}?page={{ page.previous_page_number }}">Previous</a></li>
    {% endif %}
    {% if page.has_next %}
    <li><a href="{% url 'servers:index' %}?page={{ page.next_page_number }}">Next</a></li>
    {% endif %}

</ul>
{% endif %}
{% else %}
<p>No servers are available.</p>
{% endif %}
</div>
{% endblock body %}

servers/templates/servers/snipet.html
{% load myfilters %}
<div class="server-snipet panel panel-default{% if server.rank and server.rank < 100 %} panel-warning{% endif %}">
    <a href="{{ server.get_absolute_url }}" class="panel-heading">
        {{ server.name }}
        {% if player and server.time %}
        <small> - {{server.time|timedelta}}</small>
        {% endif %}
        {% if server.rank %}<span style="float: right;">#{{ server.rank }}</span>{% endif %}
    </a>

    <div class="panel-body">
        {% if server.image_url %}
        <div>
            <img src="{{ server.image_url }}" class="hidden-xs"/>
        </div>
        {% endif %}
        <div class = "description{% if not server.description %} no-description{% endif %}">
            {% if server.description %}
            {{ server.description }}
            {% else %}
            No description has been provided for this server
            {% endif %}
        </div>
        <!--
        <ul class="tags">
            {{ server.online_mode|yesno:"<li>On-line</li>,<li>Off-line</li>,"|safe }}
            {% if server.protocol %}
            <li>{{ server.protocol }}</li>
            {% endif %}
        </ul> -->
        {% if server.online_players %}
        <b>Recently Online ({{ server.online_player_count }})</b><br />
        <div style="height: 32px; overflow: hidden;">
        {% for player in server.online_players %}
        <a href="{{ player.get_absolute_url }}"><img src="{{ player.get_absolute_url }}skin/head-32.png" width="32" height="32" style="margin-right: 4px;" data-toggle="tooltip" title="{{player}}" alt="{{player}}" /></a>
        {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

servers/templates/servers/stats.html
{% extends "base.html" %}
{% block title %}Find A Server Statistics{% endblock %}
{% block body %}
<h1>Statistics
    <small> An overview of Find A Server</small>
</h1>
{% for name, section in stats.iteritems %}
<h1>{{ name }}</h1>
<table class="table table-striped">
    {% for stat, val in section.iteritems %}
    <tr>
        <th>{{ stat }}</th>
        {% if val.1 %}
        <td class="text-right"><a href="{{ val.1 }}">{{ val.0 }}</a></td>
        {% else %}
        <td class="text-right">{{ val.0 }}</td>
        {% endif %}
    </tr>
    {% endfor %}
</table>
{% endfor %}
{% endblock body %}

servers/templates/servers/submit.html
{% extends "base.html" %}
{% block body %}
<h1>Submit A Server</h1>
{% if player.owner and player.owner == user %}
<p class="bg-info" style="padding:15px">
    You have verified your ownership of {{ player }}.
</p>
{% else %}
{% if player.owner %}
<p class="bg-warning" style="padding:15px">
    {{ player }} is already owned by {{ player.owner }}. Please only proceed if this account is yours.
</p>
{% endif %}
<p>
    This is the page to add a new server to track to the database. Duplicates are not allowed
    for various reasons and any duplicate servers will be nullified.
</p>
<form class="form-horizontal" role="form" method="post">
    {% include "form_template.html" %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Verify</button>
        </div>
    </div>
    <input type="hidden" name="next" value="{{ next }}"/>
</form>
{% endif %}
{% endblock %}

servers/templates/servers/verify.html
{% extends "base.html" %}
{% block body %}
<h1>Verify server {{ server }}</h1>
{% if not user.is_authenticated %}
<p class="bg-danger" style="padding:15px">
    You must be signed in to verify a server. Please <a href="/users/login/?next={{ server.get_absolute_url }}verify/">log
    in</a> first.
</p>
{% else %}
{% if server.owner and server.owner == user %}
<p class="bg-info" style="padding:15px">
    You own {{ server }}.
    {% if server.verification %}
    You used the {{ server.verification.get_verification_mode_display }} Method to verify.
    {% endif %}
    <a href="{% url 'management:server' server.id %}">Manage this server</a>.
</p>
{% else %}
{% if server.owner %}
<p class="bg-warning" style="padding:15px">
    {{ server }} is already owned by {{ server.owner }}.
    {% if server.verification %}
    They used the {{ server.verification.get_verification_mode_display }} Method to verify.
    {% endif %}
    Please only proceed if this server is yours.
</p>
{% endif %}
{% endif %}
<p>
    There are a few different ways to verify your ownership of a server.
</p>
<div class="col-md-6{% if not allow_dns %} method-invalid{% endif %}">
    <h2>Method 1: DNS Method</h2>
    {% if not allow_dns %}
    <p class="explanation bg-warning">
        You cannot use this method on this server as it does not use a domain.
    </p>
    {% endif %}
    <p>
        This method is the most secure method and should be used if you can. Once verified, there is no need te remove
        the verification code and will have no side effects. Keeping the code active will prevent you losing control of
        the server. This method is only applicable to servers who own their own domain names.
    </p>
    <h4>Instructions:</h4>
    <ol>
        <li>
            Edit the DNS for your server's domain name. The following string should be added to your DNS as a TXT
            record:<br/>
            <kbd>find-a-server-verification={{ verification1.verification_code }}</kbd><br/>
            If your server is on a sub-domain, the TXT record should be added to that particular sub-domain.
            <b>Do not use a wildcard record.</b>
        </li>
        <li>
            Click on this link to check your verification: <a href="{{ server.get_absolute_url }}verify/1/">Check
            verification.</a><br/>
            It may take a few hours to propagate the value through the DNS service.
        </li>
    </ol>
</div>
<div class="col-md-6">
    <h2>Method 2: MOTD Method</h2>

    <p>
        This method is the least secure - someone else can override this by performing either verification method. It
        is, however, the simplest method and should be used by server administrators without the ability to edit their
        DNS.
    </p>
    <h4>Instructions:</h4>
    <ol>
        <li>
            Edit the MOTD for your server (Usually in server.properties) to include this code:
            <kbd>{{ verification2.verification_code }}</kbd>
        </li>
        <li>
            Save the file and restart your server. (If you have a modded server it may be possible to change the MOTD
            without restarting.)
        </li>
        <li>
            Click on this link to check your verification: <a href="{{ server.get_absolute_url }}verify/2/">Check
            verification.</a>
        </li>
        <li>(Optional) Once you have checked your verification you may remove the code from your MOTD and restart your
            server again if you wish.
        </li>
    </ol>
</div>
{% endif %}
{% endblock %}