findaserver/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponse
from django.shortcuts import render

admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'findaserver.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^robots.txt$', lambda r: HttpResponse(
        "User-agent: *\nDisallow:",
        content_type="text/plain")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls')),
    url(r'^management/', include('management.urls', namespace="management")),
    # url(r'^facebook/', include('django_facebook.urls')),
    url(r'^privacy/$', lambda r: render(r, 'privacy.html')),
    url(r'^', include('servers.urls', namespace='servers')),
]

servers/urls.py
from django.conf.urls import url, include

from servers import views, server_views, skins, player_views

server_patterns = [
    url(r'^submit/', views.submit_server,
        name="submit"),
    url(r'^(?P<server_id>\d+)/', include([
        url(r'^$', server_views.server_detail,
            name='server_detail'),
        url(
            r'^verify/$', server_views.server_verify, name="server_verify"),
        url(r'^verify/(?P<type>\d)/$',
            server_views.server_verify_check),
        url(r'^players/$',
            views.player_list_with_server),
        url(
            r'^players/(?P<player_uuid>[0-9A-F]{8}'
            '(-[0-9A-F]{4}){3}-[0-9A-F]{12})/$',
            views.player_detail),
    ])),
]

player_patterns = [
    url(r'^$', views.player_list, name="players"),
    url(r'^list/$', player_views.player_list, name="player_list"),
    url(r'^by-username/$', player_views.find_player, name="player_search"),
    url(
        r'^by-username/(?P<username>[0-9A-Za-z_]{0,16})/$',
        player_views.find_player,
        name="find_player"
    ),
    url(r'^name-changes/$', player_views.recent_name_changes),
    url(
        r'^(?P<player_uuid>[0-9A-F]{8}(-[0-9A-F]{4}){3}-[0-9A-F]{12})/',
        include([
            url(r'^$', views.player_detail, name="player_detail"),
            url(r'^verify/$', views.player_verify, name="player_verify"),
            url(r'^verify_token/$', views.player_verify_token),
            url(
                r'^skin/',
                include([
                    url(r'^full.png$', skins.full, name="full_skin"),
                    url(r'^head.png$', skins.head),
                    url(r'^head-(?P<dimension>\d*).png$', skins.head),
                ])
            ),
        ])
    ),

]

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^scripts/ads.js$', views.ad),
    url(r'^servers/', include(server_patterns)),
    url(r'^players/', include(player_patterns)),
    url(r'^stats/$', views.statistics, name="stats"),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout, password_reset, \
    password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib import admin

from users.views import register, self_view, user_detail

admin.autodiscover()

urlpatterns = (
    url(r'^logout/$', logout, name="logout"),
    url(r'^login/$', login, name="login"),
    url(r'^register/$', register, name="register"),
    url(r'^reset/$', password_reset, name="password_reset"),
    url(r'^reset/sent/$', password_reset_done, name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[A-Za-z0-9]*)/(?P<token>.*)/$',
        password_reset_confirm, name="password_reset_confirm"),
    url(r'^reset/complete/$', password_reset_complete,
        name="password_reset_complete"),
    url(r'^me/$', self_view, name='self_view'),
    url(r'^info/(?P<username>[A-Za-z0-9_@+.-]*)/$',
        user_detail, name='user_info'),
)

servers/views.py
import base64
from collections import OrderedDict
from datetime import datetime, timedelta

from Crypto import Random
from Crypto.Hash import SHA

from django.core.cache import cache
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from django.db import connection
from django.db.models import Q, Sum, Max, Count
from django.http import Http404, HttpResponsePermanentRedirect, HttpResponse, \
    HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.utils.timezone import utc

from servers.models import Server, MinecraftAccount, UpTime, PlayTime, \
    UpTimeAggregate, Names
from servers import forms
from servers.templatetags import myfilters
from servers.helpers import player_count_history, top_servers_by_time, \
    top_players_by_time


_DEFAULT_PER_PAGE = 10

_SERVERS_PER_PAGE = _DEFAULT_PER_PAGE
_PLAYERS_PER_PAGE = _DEFAULT_PER_PAGE
_PLAYER_DETAILS_PER_PAGE = _DEFAULT_PER_PAGE


# Create your views here.
def index(request):
    page_num = request.GET.get('page')
    if page_num is None:
        page_num = 1
    else:
        try:
            page_num = int(page_num)
        except ValueError:
            raise Http404
        if str(page_num) != request.GET.get('page'):
            raise Http404
        if page_num == 1:
            return HttpResponsePermanentRedirect(reverse('servers:index'))
    pages = Paginator(
        Server.objects.filter(rank__isnull=False).order_by("rank"),
        _SERVERS_PER_PAGE
    )
    try:
        page = pages.page(page_num)
    except (EmptyPage, PageNotAnInteger):
        raise Http404
    cann = reverse('servers:index')
    if page.number != 1:
        cann += "?page=" + str(page.number)
    now = datetime.utcnow().replace(tzinfo=utc)
    for server in page:
        server.online_players = MinecraftAccount.objects.filter(
            playtime__server=server.id,
            playtime__end_time__gte=now - timedelta(minutes=5)
        ).annotate(
            duration=Sum("playtime__duration")
        ).order_by('-duration')
        server.online_player_count = len(server.online_players)
        server.online_players = server.online_players[:10]
    return render(request, 'servers/index.html', {
        'page': page,
        'canonical': cann,
    })


def submit_server(request):
    servers = []
    if request.method == 'POST':
        form = forms.SubmitServerForm(request.POST)
        if form.is_valid():
            return HttpResponseRedirect(
                Server.objects.create(
                    name=form.cleaned_data['server_name'],
                    address=form.cleaned_data['address'][0],
                    port=form.cleaned_data['address'][1]
                ).get_absolute_url()
            )
    else:
        form = forms.SubmitServerForm()
    return render(request, 'servers/submit.html', {
        'form': form,
        'servers': servers,
    })


def player_list(request):
    value = cache.get("player_list")
    if value:
        context = dict(value[1])
        context['valid'] = True
        return render(request, value[0], context)
    context = {
        'valid': False,
        'find_player_form': forms.PlayerHistoryForm(),
    }
    return render(request, "players/index.html", context)


def player_list_with_server(request, server_id=None):
    return render(request, *player_list_no_cache(request, server_id))


def player_list_no_cache(request, server_id=None):
    # l = logging.getLogger('django.db.backends')
    # l.setLevel(logging.DEBUG)
    # l.addHandler(logging.StreamHandler())
    now = datetime.now() # utcnow().replace(tzinfo=utc)
    if server_id is None:
        context = {
            'top_players': list(
                top_players_by_time(date_min=now - timedelta(weeks=1))[:10]
            ),
            'online': list(
                MinecraftAccount.objects.filter(
                    playtime__end_time__gte=now - timedelta(minutes=5)
                ).annotate(
                    duration=Sum("playtime__duration")
                ).order_by('-duration')[:10]
            ),
        }
    else:
        context = {
            'top_players': MinecraftAccount.objects.filter(
                playson=1
            ).annotate(
                time=Sum('playtime__duration'),
                last_on=Max('playtime__end_time')
            ).order_by('-time')[:10],
        }
    graphs = [
        {
            'element': 'player-count-graph',
            'type': 'AreaChart',
            'package': 'corechart',
            'cols': [
                {
                    'id': 'Date',
                    'type': 'date',
                },
                {
                    'id': 'Players',
                    'type': 'number',
                },
            ],
        }
    ]

    if server_id is None:
        context['find_player_form'] = forms.PlayerHistoryForm()
        query = "SELECT `checkTime`, SUM(`playerCount`) as players FROM "\
                "`servers_uptimeaggregate` WHERE checkTime > UTC_TIMESTAMP() "\
                "- INTERVAL 1 WEEK GROUP BY `checkTime`"
        with connection.cursor() as cursor:
            cursor.execute(query)
            data = cursor.fetchall()
            if data:
                rounded_now = now.replace(
                    second=0,
                    microsecond=0,
                    minute=10*(now.minute/10)
                )
                graphs[0]['data'] = player_count_history(
                    rounded_now - timedelta(weeks=1),
                    rounded_now,
                    timedelta(minutes=30),
                    (
                        {
                            'checkTime': up[0],
                            'playerCount': up[1],
                        } for up in data
                    )
                )
    else:
        graphs[0]['data'] = player_count_history(
            datetime.utcnow().replace(tzinfo=utc) - timedelta(weeks=1),
            datetime.utcnow().replace(tzinfo=utc), timedelta(minutes=30),
            UpTime.objects.filter(
                server=server_id,
                checkTime__gte=(
                    datetime.utcnow().replace(tzinfo=utc) - timedelta(weeks=1)
                ),
                status=1
            ).values('checkTime', 'server_id', 'delta', 'playerCount')
        )
    context['graphs'] = graphs
    return 'players/index.html', context


def player_detail(request, player_uuid, server_id=None):
    # __iexact because django/mysql bug.
    player = get_object_or_404(
        MinecraftAccount,
        UUID__iexact=int("".join(player_uuid.split("-")), 16)
    )
    now = datetime.utcnow().replace(tzinfo=utc)
    context = {
        'player': player,
        'top_servers': top_servers_by_time(player.id)[:5],
        'recent_playtime': PlayTime.objects.filter(
            minecraft_account=player
        ).order_by('-end_time')[:10],
        'votes': Server.objects.filter(
            Q(vote__time__gte=now - timedelta(weeks=1)) & (
                Q(vote__minecraft_account=player) |
                Q(vote__minecraft_name=player.name)
            )
        ).annotate(count=Count('vote__time')),
    }
    data = PlayTime.objects.filter(
        minecraft_account=player,
        end_time__gte=now - timedelta(weeks=1)
    ).select_related('server')
    if data:
        context['graphs'] = [
            {
                'element': 'playtime-graph',
                'type': 'Timeline',
                'package': 'timeline',
                'cols': [
                    {
                        'id': 'Server',
                        'type': 'string',
                    },
                    {
                        'id': 'Start',
                        'type': 'date',
                    },
                    {
                        'id': 'End',
                        'type': 'date',
                    },
                ],
                'data': (
                    (
                        "'%s'" % s.server.name,
                        "new Date(%s)" % (
                            (s.end_time - timedelta(
                                seconds=s.duration + 1
                            )).strftime("%s") + "000"
                        ),
                        "new Date(%s)" % (
                            s.end_time.strftime("%s") + "000"
                        ),
                    ) for s in data
                ),
                'options': """{
                    hAxis: {
                        viewWindowMode:'explicit',
                        viewWindow: {
                            min: new Date(%s),
                            max: new Date(%s)
                        }
                    }
                }""" % (
                    (now - timedelta(weeks=4)).strftime("%s") + "000",
                    now.strftime("%s") + "000",
                ),
            },
        ]

    # pages = Paginator(Server.objects.all().order_by("-name"),
    #                   _SERVERS_PER_PAGE)
    # TODO
    return render(request, 'players/detail.html', context)


def player_verify(request, player_uuid):
    player = get_object_or_404(
        MinecraftAccount,
        UUID__iexact=int("".join(player_uuid.split("-")), 16)
    )
    if request.method == 'POST':
        form = forms.PlayerVerifyForm(request.POST)
        if form.is_valid() and request.user.is_authenticated():
            if form.cleaned_data['token'] == player.verification_code:
                # TODO: timestamp
                player.owner = request.user
                player.save()
    else:
        form = forms.PlayerVerifyForm()
    return render(request, 'players/verify.html', {
        'player': player,
        'form': form
    })


# Called by the minecraft server to fetch a token for a user.
def player_verify_token(request, player_uuid):
    if not request.GET.get('hash'):
        raise Http404
    # TODO: Move Shared secret to settings?

servers/templates/players/detail.html
{% extends "base.html" %}
{% block title %}{{ player }} Minecraft Account{% endblock %}
{% block body %}
<h1>{{ player }}</h1>
<div class="row">
    <div class="col-sm-3 col-md-2">
        <img src="{{ player.get_absolute_url }}skin/head-128.png" width="128" height="128" alt="Face of {{ player }}"/>
    </div>
    <div class="col-sm-9 col-md-8">
        <h2>About {{ player }}</h2>
        {% if not player.owner %}
        {{ player }} is not currently owned. Do you own {{ player }}? You can verify your ownership
        on the <a href="{{ player.get_absolute_url }}verify/">verify page</a>.
        {% elif player.owner == user %}
        You own {{ player }}.
        {% else %}
        {{ player }} is owned by {{ player.owner }}. Are you the rightful owner? Please verify your ownership on the
        <a href="{{ player.get_absolute_url }}verify/">verify page</a>.
        {% endif %}
    </div>
</div>
<div class="col-md-9">
    {% if top_servers %}
    <h2>Most Played Servers</h2>
    {% for server in top_servers %}
    {% include "servers/snipet.html" %}
    {% endfor %}
    {% endif %}
    <h2>Recent Gameplay</h2>

    <div id="playtime-graph"></div>
    {% for session in recent_playtime %}
    {% ifchanged %}<h3>{{ session.end_time|date:"jS F" }}</h3>{% endifchanged %}
    <div>
        {{session}}
    </div>
    {% empty %}
    <p class="bg-info" style="padding:15px;">
        This player has no play sessions tracked.
    </p>
    {% endfor %}
</div>
<div class="col-md-3">
    <h2>Recent Votes</h2>
    {% for server in votes %}
    <div>
        Voted for {{ server }} {{ server.count }} time{{ server.count|pluralize }}
    </div>
    {% empty %}
    <p class="bg-info" style="padding:15px;">
        This player has not voted for any servers recently. Perhaps you should invite them to vote!
    </p>
    {% endfor %}
</div>
{% endblock body %}

servers/templates/players/history-by-username.html
{% extends "base.html" %}
{% block title %}Username history of {{ username }}{% endblock %}
{% block body %}

<h2>Username History of {{ username }}</h2>
<p class="bg-info">
    This is a list of all the name changes we've detected for this username. As we only check names when we detect them
    on servers with the Advanced Query enabled this may not be a complete list of all changes and dates may be
    inaccurate.
    The current user is always shown in green.
</p>
<table class="table">
    <tr>
        <th>Current Skin</th>
        <th>Used As</th>
        <th>Current Username</th>
        <th>Used Dates</th>
    </tr>
    {% for holder in holders %}
    <tr
    {% if current_holder and holder.minecraft_account_id == current_holder.id %} class="success"{% endif %}>
    <td>
        <a href="{{ holder.minecraft_account.get_absolute_url }}">
            <img src="{{ holder.minecraft_account.get_absolute_url }}skin/head-64.png" height="64" width="64" alt="Current Face of {{holder.minecraft_account}}"/>
        </a>
    </td>
    <td>{{ holder.name }}</td>
    <td><a href="{{ holder.minecraft_account.get_absolute_url }}">{{ holder.minecraft_account.name }}</a></td>
    <td>{% if holder.end %}{{holder.start}} - {{holder.end}}{% else %}Since {{holder.start}}{%endif%}</td>
    </tr>
    {% endfor %}
</table>
{% endblock body %}

servers/templates/players/history-form.html
{% extends "base.html" %}
{% block title %}Find a Player - Where has a minecraft account been playing recently?{% endblock %}
{% block body %}
<h1>Find a Player</h1>
<p>
    Haven't seen a player in a long time? Miss your friend? Or maybe you just want to look your own account up, this is
    the place to do it.
</p>
<form class="form-horizontal" role="form" method="post" action="{% url 'servers:player_search' %}">
    {% include "form_template.html" %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Find</button>
        </div>
    </div>
</form>
{% if suggestions %}
<h3>Did you mean..?</h3>
<p class="bg-info">Here's some tracked users that are like the one you requested.</p>
<ul class="list-unstyled player-list">
{% for user in suggestions %}
<li class="col-xs-12 col-sm-6 col-md-3" style="padding:5px;">
    <img src="{{ user.minecraft_account.get_absolute_url }}skin/head-64.png" height="64" width="64" alt="Face of {{user.minecraft_account }}"/>
    <div>
        <a href="{% url "servers:find_player" user.name %}" >{{ user.name }}</a>
    </div>
</li>
{% endfor %}
{% endif %}
{% endblock body %}

servers/templates/players/index.html
{% extends "base.html" %}
{% block body %}
{% load myfilters %}
<div class="row">
<div{% if find_player_form %} class="col-md-6"{% endif %}><div id="player-count-graph">{% if not valid %}
<h3>Server Error</h3>
<p>We are currently unable to generate content for this page. We are sorry for any inconvenience caused.</p>
{% endif %}</div></div>
{% if find_player_form %}
<div class="col-md-6">
    <h2>Find a Player <small><a href="/players/list/">browse all</a></small></h2>

    <form class="form-horizontal" role="form" method="post" action="{% url 'servers:player_search' %}">
        {% include "form_template.html" with form=find_player_form %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Find</button>
            </div>
        </div>
    </form>
</div>
{% endif %}
</div>
{% if top_players %}
<div class="col-sm-6 col-lg-3">
    <h2>Top Players</h2>
    <ul class="list-unstyled player-list">
        {% for player in top_players %}
        <li class="col-xs-12">
            <img src="{{ player.get_absolute_url }}skin/head-64.png" width="64" height="64" alt="Face of {{player}}"/>

            <div>
                <a href="{{ player.get_absolute_url }}">{{ player.name}}</a><br/>{{player.time|timedelta}}
            </div>
        </li>
        {% endfor %}
    </ul>
    <div class="clearfix"></div>
</div>
{% endif %}

{% if online %}
<div class="col-sm-6 col-lg-3">
    <h2>Online Now</h2>
    <ul class="list-unstyled player-list">
        {% for player in online %}
        <li class="col-xs-12">
            <img src="{{ player.get_absolute_url }}skin/head-64.png" width="64" height="64" alt="Face of {{player}}"/>

            <div>
                <a href="{{ player.get_absolute_url }}">{{ player.name}}</a><br/>Playing for
                {{player.duration|timedelta}}
            </div>
        </li>
        {% endfor %}
    </ul>
    <div class="clearfix"></div>
</div>
{% endif %}
{% endblock body %}

servers/templates/players/list.html
{% extends "base.html" %}
{% block body %}
{% load myfilters %}
<h1>All Players</h1>
<div class="row">
{% if page %}
{% for player in page %}
<div class="col-sm-6 col-lg-3" style="min-height:70px;">
    <img src="{{ player.get_absolute_url }}skin/head-64.png" width="64" height="64" alt="Face of {{player}}" style="position: absolute;"/>
    <div>
        <a href="{{ player.get_absolute_url }}" style="padding-left: 70px;">{{ player.name}}</a><br/>
    </div>
</div>
{% endfor %}
</div>
{% if page.has_other_pages %}
<ul class="pager">
    {% if page.has_previous %}
    <li><a href="{% url 'servers:player_list' %}?page={{ page.previous_page_number }}">Previous</a></li>
    {% endif %}
    {% if page.has_next %}
    <li><a href="{% url 'servers:player_list' %}?page={{ page.next_page_number }}">Next</a></li>
    {% endif %}

</ul>
{% endif %}
{% endif %}
{% endblock body %}

servers/templates/players/recent-name-changes.html
{% extends "base.html" %}
{% block title %}Recent Username Changes{% endblock %}
{% block body %}

<h2>Recent Username Changes</h2>
<table class="table">
    <tr>
        <th>Current Skin</th>
        <th>Changed From</th>
        <th>Current Username</th>
        <th>Used Dates</th>
    </tr>
    {% for change in changes %}
    <tr>
    <td>
        <a href="{{ change.minecraft_account.get_absolute_url }}">
            <img src="{{ change.minecraft_account.get_absolute_url }}skin/head-64.png" height="64" width="64" alt="Current Face of {{change.minecraft_account}}"/>
        </a>
    </td>
    <td>{{ change.name }}</td>
    <td><a href="{{ change.minecraft_account.get_absolute_url }}">{{ change.minecraft_account.name }}</a></td>
    <td>{{change.start}} - {{change.end}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock body %}

servers/templates/players/verify.html
{% extends "base.html" %}
{% block body %}
<h1>Verify player {{ player }}</h1>
{% if not user.is_authenticated %}
<p class="bg-danger" style="padding:15px">
    You must be signed in to verify an account. Please <a href="{% url 'login' %}?next={{ player.get_absolute_url }}verify/">log
    in</a> first.
</p>
{% else %}
{% if player.owner and player.owner == user %}
<p class="bg-info" style="padding:15px">
    You have verified your ownership of {{ player }}.
</p>
{% else %}
{% if player.owner %}
<p class="bg-warning" style="padding:15px">
    {{ player }} is already owned by {{ player.owner }}. Please only proceed if this account is yours.
</p>
{% endif %}
<p>
    To verify your account, you must sign in to the Find A Server authentication server using a minecraft client.
    Simply open your Minecraft client and connect to the server at <kbd>find-a-server.com</kbd>. You will be given
    an 8 digit code that you should enter on this page to verify your account.
</p>
<form class="form-horizontal" role="form" method="post" action="{{ player.get_absolute_url }}verify/">
    {% include "form_template.html" %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Verify</button>
        </div>
    </div>
    <input type="hidden" name="next" value="{{ next }}"/>
</form>
{% endif %}
{% endif %}
{% endblock %}